export const products = [
    {
        id: '001',
        name: 'Ergonomic Concrete Lamp',
        price: 569.31,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/31.jpg',
        stars: 4.2,
    },
    {
        id: '002',
        name: 'Apple',
        price: 569.31,
        stars: 4.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/4.jpg',
    },
    {
        id: '003',
        name: 'Apple',
        price: 569.31,
        stars: 3.9,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/28.jpg',
    },
    {
        id: '004',
        name: 'Apple',
        price: 569.31,
        stars: 2.2,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/27.jpg',
    },
    {
        id: '006',
        name: 'Aerodynamic Paper Chair',
        price: 569.31,
        stars: 3.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/5.jpg',
    },
    {
        id: '007',
        name: 'Ergonomic Concrete Lamp',
        price: 569.31,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/1.jpg',
        stars: 4.2,
    },
    {
        id: '008',
        name: 'Apple',
        price: 569.31,
        stars: 4.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/3.jpg',
    },
    {
        id: '009',
        name: 'Apple',
        price: 569.31,
        stars: 3.9,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/2.jpg',
    },
    {
        id: '010',
        name: 'Apple',
        price: 569.31,
        stars: 2.2,
        image: 'http://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/9.jpg',
    },
    {
        id: '011',
        name: 'Aerodynamic Paper Chair',
        price: 569.31,
        stars: 3.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/15.jpg',
    },
    {
        id: '001',
        name: 'Ergonomic Concrete Lamp',
        price: 569.31,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/31.jpg',
        stars: 4.2,
    },
    {
        id: '002',
        name: 'Apple',
        price: 569.31,
        stars: 4.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/4.jpg',
    },
    {
        id: '003',
        name: 'Apple',
        price: 569.31,
        stars: 3.9,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/28.jpg',
    },
    {
        id: '004',
        name: 'Apple',
        price: 569.31,
        stars: 2.2,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/27.jpg',
    },
    {
        id: '006',
        name: 'Aerodynamic Paper Chair',
        price: 569.31,
        stars: 3.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/5.jpg',
    },
    {
        id: '007',
        name: 'Ergonomic Concrete Lamp',
        price: 569.31,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/1.jpg',
        stars: 4.2,
    },
    {
        id: '008',
        name: 'Apple',
        price: 569.31,
        stars: 4.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/3.jpg',
    },
    {
        id: '009',
        name: 'Apple',
        price: 569.31,
        stars: 3.9,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/2.jpg',
    },
    {
        id: '010',
        name: 'Apple',
        price: 569.31,
        stars: 2.2,
        image: 'http://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/9.jpg',
    },
    {
        id: '011',
        name: 'Aerodynamic Paper Chair',
        price: 569.31,
        stars: 3.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/15.jpg',
    },
    {
        id: '001',
        name: 'Ergonomic Concrete Lamp',
        price: 569.31,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/31.jpg',
        stars: 4.2,
    },
    {
        id: '002',
        name: 'Apple',
        price: 569.31,
        stars: 4.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/4.jpg',
    },
    {
        id: '003',
        name: 'Apple',
        price: 569.31,
        stars: 3.9,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/28.jpg',
    },
    {
        id: '004',
        name: 'Apple',
        price: 569.31,
        stars: 2.2,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/27.jpg',
    },
    {
        id: '006',
        name: 'Aerodynamic Paper Chair',
        price: 569.31,
        stars: 3.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/5.jpg',
    },
    {
        id: '007',
        name: 'Ergonomic Concrete Lamp',
        price: 569.31,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/1.jpg',
        stars: 4.2,
    },
    {
        id: '008',
        name: 'Apple',
        price: 569.31,
        stars: 4.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/3.jpg',
    },
    {
        id: '009',
        name: 'Apple',
        price: 569.31,
        stars: 3.9,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/2.jpg',
    },
    {
        id: '010',
        name: 'Apple',
        price: 569.31,
        stars: 2.2,
        image: 'http://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/9.jpg',
    },
    {
        id: '011',
        name: 'Aerodynamic Paper Chair',
        price: 569.31,
        stars: 3.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/15.jpg',
    },
    {
        id: '001',
        name: 'Ergonomic Concrete Lamp',
        price: 569.31,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/31.jpg',
        stars: 4.2,
    },
    {
        id: '002',
        name: 'Apple',
        price: 569.31,
        stars: 4.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/4.jpg',
    },
    {
        id: '003',
        name: 'Apple',
        price: 569.31,
        stars: 3.9,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/28.jpg',
    },
    {
        id: '004',
        name: 'Apple',
        price: 569.31,
        stars: 2.2,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/27.jpg',
    },
    {
        id: '006',
        name: 'Aerodynamic Paper Chair',
        price: 569.31,
        stars: 3.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/5.jpg',
    },
    {
        id: '007',
        name: 'Ergonomic Concrete Lamp',
        price: 569.31,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/1.jpg',
        stars: 4.2,
    },
    {
        id: '008',
        name: 'Apple',
        price: 569.31,
        stars: 4.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/3.jpg',
    },
    {
        id: '009',
        name: 'Apple',
        price: 569.31,
        stars: 3.9,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/2.jpg',
    },
    {
        id: '010',
        name: 'Apple',
        price: 569.31,
        stars: 2.2,
        image: 'http://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/9.jpg',
    },
    {
        id: '011',
        name: 'Aerodynamic Paper Chair',
        price: 569.31,
        stars: 3.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/15.jpg',
    },
    {
        id: '001',
        name: 'Ergonomic Concrete Lamp',
        price: 569.31,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/31.jpg',
        stars: 4.2,
    },
    {
        id: '002',
        name: 'Apple',
        price: 569.31,
        stars: 4.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/4.jpg',
    },
    {
        id: '003',
        name: 'Apple',
        price: 569.31,
        stars: 3.9,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/28.jpg',
    },
    {
        id: '004',
        name: 'Apple',
        price: 569.31,
        stars: 2.2,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/27.jpg',
    },
    {
        id: '006',
        name: 'Aerodynamic Paper Chair',
        price: 569.31,
        stars: 3.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/5.jpg',
    },
    {
        id: '007',
        name: 'Ergonomic Concrete Lamp',
        price: 569.31,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/1.jpg',
        stars: 4.2,
    },
    {
        id: '008',
        name: 'Apple',
        price: 569.31,
        stars: 4.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/3.jpg',
    },
    {
        id: '009',
        name: 'Apple',
        price: 569.31,
        stars: 3.9,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/2.jpg',
    },
    {
        id: '010',
        name: 'Apple',
        price: 569.31,
        stars: 2.2,
        image: 'http://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/9.jpg',
    },
    {
        id: '011',
        name: 'Aerodynamic Paper Chair',
        price: 569.31,
        stars: 3.4,
        image: 'https://demo2wpopal.b-cdn.net/freshio/wp-content/uploads/2020/08/15.jpg',
    },
];

export const navLinks = [
    {
        name: 'Home',
        to: '/',
    },
    {
        name: 'Products',
        to: '/products',
    },

    {
        name: 'Blog',
        to: '/blog',
    },
    {
        name: 'Contact',
        to: '/contact',
    },
    {
        name: 'More',
        to: '#',
        dropdown: [
            {
                name: 'About',
                to: '/about',
            },
            {
                name: 'Our Gallery',
                to: '/gallery',
            },
            {
                name: 'Admin',
                to: '/admin',
            },
        ],
    },
];

export const monthNames = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
];

export const states = [
    'andhra pradesh',
    'arunachal pradesh',
    'assam',
    'bihar',
    'chhattisgarh',
    'goa',
    'gujarat',
    'haryana',
    'himachal pradesh',
    'jammu and kashmir',
    'jharkhand',
    'karnataka',
    'kerala',
    'madhya pradesh',
    'maharashtra',
    'manipur',
    'meghalaya',
    'mizoram',
    'nagaland',
    'odisha',
    'punjab',
    'rajasthan',
    'sikkim',
    'tamil nadu',
    'telangana',
    'tripura',
    'uttarakhand',
    'uttar pradesh',
    'west bengal',
    'andaman and nicobar islands',
    'chandigarh',
    'dadra and nagar haveli',
    'daman and diu',
    'delhi',
    'lakshadweep',
    'puducherry',
];
